import dotenv from 'dotenv'

dotenv.config()
const { TOKEN, APPLICATION_ID, GUILD_ID, FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_PROJECT_ID, FIREBASE_STORAGE_BUCKET, FIREBASE_MESSAGING_SENDER_ID, FIREBASE_APP_ID, FIREBASE_DATABASE_URL } = process.env

if (!TOKEN || !APPLICATION_ID || !GUILD_ID) {
  throw new Error('Missing env variables')
}

if (!FIREBASE_API_KEY || !FIREBASE_AUTH_DOMAIN || !FIREBASE_PROJECT_ID || !FIREBASE_STORAGE_BUCKET || !FIREBASE_MESSAGING_SENDER_ID || !FIREBASE_APP_ID || !FIREBASE_DATABASE_URL) {
  throw new Error('Missing env variables for firebase')
}

const config: Record<string, string> = {
  APPLICATION_ID,
  TOKEN,
  GUILD_ID,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_DATABASE_URL
}

export default config
